[build]
  command = "chmod +x ./netlify-prebuild.sh && ./netlify-prebuild.sh && SKIP_TYPE_CHECK=1 NEXT_IGNORE_ESLINT=1 NEXT_USE_STATIC_EXPORT=true NEXT_PUBLIC_SKIP_API_ROUTES=true next build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_IGNORE_ESLINT = "1"
  ESLINT_IGNORE_ERRORS = "true"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-audit --no-fund --force"
  NEXT_DISABLE_STATIC = "1"
  NEXT_USE_STATIC_EXPORT = "true"
  NEXT_PUBLIC_SKIP_API_ROUTES = "true"
  SKIP_TYPE_CHECK = "1"
  NODE_VERSION = "20"

# This makes sure API routes are handled correctly by our Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Default SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets 
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 